function fig = data_input()

% GUI INTERFACE: Strings and text-box input
%
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

% list of handles :
% tag: data_box
% tag: instruction_string
% tag: end_string
% tag: start
% tag: quit

%global DATA_VALUE_STORED;

load data_input
load max_screen;

size_screen = get(0,'screensize');
h_screen = size_screen(4);
w_screen = size_screen(3);

h_const = 0.1;
w_const = 0.8;

% root figure
h0 = figure('Units','normalized',...
	'Color',[0.2431 0.2431 0.4824], ...
	'Colormap',mat0, ...
	'FileName','C:\Home\olivier\PROGRAM\Matlab\interfaces\data_input.m', ...
	'MenuBar','none', ...
	'PaperPositionMode','auto', ...
	'PaperUnits','points', ...
	'Position',[max_screen], ...
	'Tag','Fig1', ...
	'ToolBar','none', ...
	'WindowStyle','normal'); % 'modal' hides matlab window
% debugging string
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.2431 0.2431 0.4824], ...
	'FontUnits','normalized',...
	'FontName','Courrier', ...
	'FontSize',0.1, ...
	'ForegroundColor',[1 1 1], ...
	'Position',[0 .7 .6 .2], ...
	'String','', ...
	'Style','text', ...
	'Tag','debug_string');
% input area
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontUnits','normalized', ...
	'FontName','Times', ...
	'FontSize',0.7, ...
	'FontWeight','bold', ...
	'ForegroundColor',[0.2431 0.2431 0.4824], ...
	'Position',[.3 .5 .4 .05], ...
	'String','', ...
	'Style','edit', ...
	'Tag','data_box', ...
	'Callback','test_envelope_callbacks store;');
% Instruction string
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.2431 0.2431 0.4824], ...
	'FontUnits','normalized',...
	'FontName','Helvetica', ...
	'FontSize',0.3, ...
	'ForegroundColor',[1 1 1], ...
	'Position',[.3 .3 .4 .1], ...
	'String','Type the digit sequence you''ve identified inside the box above', ...
	'Style','text', ...
	'Tag','instruction_string');
% Messages
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.2431 0.2431 0.4824], ...
	'FontUnits','normalized',...
	'FontName','Helvetica', ...
	'FontSize',0.25, ...
	'ForegroundColor',[1 1 1], ...
	'Position',[.1 .8 .3 .1], ...
	'String','', ...
	'Style','text', ...
	'Tag','msg_string');
% End of experiment string
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.2431 0.2431 0.4824], ...
	'FontUnits','normalized',...
	'FontName','Helvetica', ...
	'FontSize',0.3, ...
	'ForegroundColor',[1 1 1], ...
	'Position',[.3 .5 .4 .1], ...
	'String','You''ve reached the end of the experiment. Thanks for your help.', ...
	'Style','text', ...
	'Tag','end_string');
% start button
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
	'Style','pushbutton', ...
	'FontUnits','normalized',...
	'FontSize',0.4, ...
	'FontWeight','bold', ...
	'ForegroundColor',[0.2431 0.2431 0.4824], ...
	'Position',[w_const+.07 3*(h_const+.12)/2 .1 3*.03/2], ...
	'String','Start', ...
	'Tag','start',...
	'Callback','onset=1;');
% quit button
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
	'Style','pushbutton', ...
	'FontUnits','normalized',...
	'FontSize',0.4, ...
	'FontWeight','bold', ...
	'ForegroundColor',[0.2431 0.2431 0.4824], ...
	'Position',[w_const+.07 3*(h_const+.02)/2 .1 3*.03/2], ...
	'String','Quit', ...
	'Tag','quit',...
	'Callback','endofexperiment=1;');
if nargout > 0, fig = h0; end
