function fig = data_input()

% GUI INTERFACE: Essais
%
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load data_input
load max_screen;

size_screen = get(0,'screensize');
h_screen = size_screen(4);
w_screen = size_screen(3);

h_const = 0.1;
w_const = 0.8;

h0 = figure('Units','normalized',...
	'Color',[0.50 0.50 0.75], ...
	'Colormap',mat0, ...
	'FileName','C:\Home\olivier\PROGRAM\Matlab\interfaces\data_input.m', ...
	'MenuBar','none', ...
	'PaperPositionMode','auto', ...
	'PaperUnits','points', ...
	'Position',max_screen, ...
   'Tag','Fig1', ...
   'ToolBar','none', ...
   'WindowStyle','normal'); % 'modal' hides matlab window
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
   'FontUnits','normalized',...
   'FontSize',0.2, ...
	'Position',[.3 .5 .4 .05], ...
	'Style','edit', ...
   'Tag','data_box', ...
   'Callback','test_envelope_callbacks store');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.50 0.50 0.75], ...
   'FontUnits','normalized',...
   'FontSize',0.3, ...
	'ForegroundColor',[1 1 1], ...
	'Position',[.3 .3 .4 .1], ...
	'String','Type the digit sequence you''ve identified inside the box above', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
	'Style','pushbutton', ...
   'FontUnits','normalized',...
   'FontSize',0.4, ...
	'FontWeight','bold', ...
	'Position',[w_const+.07 3*(h_const+.12)/2 .1 3*.03/2], ...
	'String','Start', ...
   'Tag','Start',...
   'Callback','onset=1;');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
	'Style','pushbutton', ...
   'FontUnits','normalized',...
   'FontSize',0.4, ...
	'FontWeight','bold', ...
	'Position',[w_const+.07 3*(h_const+.02)/2 .1 3*.03/2], ...
	'String','Quit', ...
   'Tag','Quit',...
   'Callback','test_envelope_callbacks finish');
h1 = axes('Parent',h0, ...
   'Units','normalized', ...
   'Box','on', ...
   'Color','none', ...
   'FontUnits','normalized',...
   'FontSize',0.05, ...
	'Position',[.03 3*(.03)/2 .2 3*.2/2]);
if nargout > 0, fig = h0; end
