function interface_seuils_6AFC()

% GUI INTERFACE: mot vs non-mot, 6 confidence levels (3 per category)
%
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load interface_seuils_6AFC             

a = figure('Units','points', ...
   'Color',[0 0 0], ...
   'menubar','none', ...
   'Colormap',mat0, ...
	'PointerShapeCData',mat1, ...
	'Position',[0 0 600 435.75], ...
	'Tag','Interface_seuils_6AFC');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','answer = 1;', ...
   'Fontname','times', ...
   'FontSize',13, ...
	'FontWeight','bold', ...
	'Position',[59 210 61.5 84.75], ...
	'String','non-mot', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','answer = 2;', ...
   'Fontname','times', ...
	'FontSize',10, ...
	'FontWeight','bold', ...
	'Position',[133 210 61.5 84.75], ...
	'String','non-mot', ...
	'Tag','Pushbutton2');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','answer = 3;', ...
   'Fontname','times', ...
	'FontSize',6, ...
	'FontWeight','bold', ...
	'Position',[207 210 61.5 84.75], ...
	'String','non-mot', ...
	'Tag','Pushbutton3');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','answer = 4;', ...
   'Fontname','times', ...
	'FontSize',6, ...
	'FontWeight','bold', ...
	'Position',[336 210 61.5 84.75], ...
	'String','mot', ...
	'Tag','Pushbutton4');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','answer = 5;', ...
   'Fontname','times', ...
	'FontSize',10, ...
	'FontWeight','bold', ...
	'Position',[408 210 61.5 84.75], ...
	'String','mot', ...
	'Tag','Pushbutton5');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','answer = 6;', ...
   'Fontname','times', ...
	'FontSize',13, ...
	'FontWeight','bold', ...
	'Position',[479 210 61.5 84.75], ...
	'String','mot', ...
	'Tag','Pushbutton6');
%b = uicontrol('Parent',a, ...
%	'Units','points', ...
%	'BackgroundColor',[0.3 1 0.3], ...
%   'Fontname','times', ...
%	'FontSize',12, ...
%	'FontWeight','bold', ...
%	'Position',[59 187 61.5 21], ...
%	'Style','text', ...
%	'Tag','StaticText1');
%b = uicontrol('Parent',a, ...
%	'Units','points', ...
%	'BackgroundColor',[0.5 1 0.5], ...
%  'Fontname','times', ...
%	'FontSize',10, ...
%	'Position',[133 187 61.5 21], ...
%	'Style','text', ...
%	'Tag','StaticText2');
%b = uicontrol('Parent',a, ...
%	'Units','points', ...
%	'BackgroundColor',[0.7 1 0.7], ...
%   'Fontname','times', ...
%	'Position',[207 187 61.5 21], ...
%	'Style','text', ...
%	'Tag','StaticText3');
%b = uicontrol('Parent',a, ...
%	'Units','points', ...
%	'BackgroundColor',[1 0.7 0.7], ...
%   'Fontname','times', ...
%	'Position',[336 187 61.5 21], ...
%	'Style','text', ...
%	'Tag','StaticText4');
%b = uicontrol('Parent',a, ...
%	'Units','points', ...
%	'BackgroundColor',[1 0.5 0.5], ...
%	'Enable','off', ...
%   'Fontname','times', ...
%	'FontSize',10, ...
%	'Position',[408 187 61.5 21], ...
%	'Style','text', ...
%	'Tag','StaticText5');
%b = uicontrol('Parent',a, ...
%	'Units','points', ...
%	'BackgroundColor',[1 0.3 0.3], ...
%   'Fontname','times', ...
%	'FontSize',12, ...
%	'FontWeight','bold', ...
%	'Position',[479 187 61.5 21], ...
%	'Style','text', ...
%	'Tag','StaticText6');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','debut=1;', ...
   'Fontname','times', ...
	'Position',[420.75 21 167.25 19.5], ...
	'String','Lancer l''expérience', ...
	'Tag','Pushbutton_Debut');
