function fig = phone_pad()

% GUI INTERFACE: Phone pad
%
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load phone_pad
load max_screen;

h_const = 0.1;
w_const = 0.8;

h0 = figure('Units','normalized', ...
	'Color',[0.50 0.50 0.75], ...
	'Colormap',mat0, ...
	'FileName','C:\Home\olivier\PROGRAM\Matlab\interfaces\phone_pad.m', ...
	'MenuBar','none', ...
	'PaperPositionMode','auto', ...
	'Position',max_screen, ...
	'Tag','Fig1', ...
	'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
   'FontUnits','normalized', ...
   'FontSize',.3, ...
	'FontWeight','normal', ...
	'String','1', ...
	'ListboxTop',0, ...
	'Position',[w_const+.02 3*(h_const+.02)/2 .05 3*.05/2], ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
   'FontUnits','normalized', ...
   'FontSize',.3, ...
	'FontWeight','normal', ...
	'String','2', ...
	'ListboxTop',0, ...
	'Position',[w_const+.07 3*(h_const+.02)/2 .05 3*.05/2], ...
	'Tag','Pushbutton2');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
   'FontUnits','normalized', ...
   'FontSize',.3, ...
	'FontWeight','normal', ...
	'String','3', ...
	'ListboxTop',0, ...
	'Position',[w_const+.12 3*(h_const+.02)/2 .05 3*.05/2], ...
	'Tag','Pushbutton3');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
   'FontUnits','normalized', ...
   'FontSize',.3, ...
	'FontWeight','normal', ...
	'String','4', ...
	'ListboxTop',0, ...
	'Position',[w_const+.02 3*(h_const+.07)/2 .05 3*.05/2], ...
	'Tag','Pushbutton4');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
   'FontUnits','normalized', ...
   'FontSize',.3, ...
	'FontWeight','normal', ...
	'String','5', ...
	'ListboxTop',0, ...
	'Position',[w_const+.07 3*(h_const+.07)/2 .05 3*.05/2], ...
	'Tag','Pushbutton5');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
   'FontUnits','normalized', ...
   'FontSize',.3, ...
	'FontWeight','normal', ...
	'String','6', ...
	'ListboxTop',0, ...
	'Position',[w_const+.12 3*(h_const+.07)/2 .05 3*.05/2], ...
	'Tag','Pushbutton6');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
   'FontUnits','normalized', ...
   'FontSize',.3, ...
	'FontWeight','normal', ...
	'String','7', ...
	'ListboxTop',0, ...
	'Position',[w_const+.02 3*(h_const+.12)/2 .05 3*.05/2], ...
	'Tag','Pushbutton7');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
   'FontUnits','normalized', ...
   'FontSize',.3, ...
	'FontWeight','normal', ...
	'String','8', ...
	'ListboxTop',0, ...
	'Position',[w_const+.07 3*(h_const+.12)/2 .05 3*.05/2], ...
	'Tag','Pushbutton8');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
   'FontUnits','normalized', ...
   'FontSize',.3, ...
	'FontWeight','normal', ...
	'String','9', ...
	'ListboxTop',0, ...
	'Position',[w_const+.12 3*(h_const+.12)/2 .05 3*.05/2], ...
	'Tag','Pushbutton9');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
   'FontUnits','normalized', ...
   'FontSize',.3, ...
	'FontWeight','normal', ...
	'String','0', ...
	'ListboxTop',0, ...
	'Position',[w_const+.07 3*(h_const-.03)/2 .05 3*.05/2], ...
	'Tag','Pushbutton0');
if nargout > 0, fig = h0; end
